version: "3.9"

services:
  web:
    build: .
    container_name: fastapi-app
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --reload
    volumes:
      - .:/app
      - ./resources:/app/resources
    ports:
      - "7000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://sharif:password@localhost:5432/pooz_store

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"

  # Optional: DB viewer
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
