"""brand created

Revision ID: 2cb720387109
Revises: 5f20bcf7b66b
Create Date: 2025-05-22 17:37:49.119081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cb720387109'
down_revision: Union[str, None] = '5f20bcf7b66b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # op.create_table('brands',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('description', sa.VARCHAR(length=511), autoincrement=False, nullable=True),
    # sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    # sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    # sa.Column('created_at', sa.VARCHAR(length=50), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('updated_at', sa.VARCHAR(length=50), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    # sa.Column('sub_category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    # sa.ForeignKeyConstraint(['sub_category_id'], ['sub_categories.id'], name='brands_sub_category_id_fkey'),
    # sa.PrimaryKeyConstraint('id', name='brands_pkey')
    # )
    # with op.batch_alter_table('brands', schema=None) as batch_op:
    #     batch_op.create_index('ix_brands_id', ['id'], unique=False)
    pass
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('brands')
    pass
    