"""remove sub_category_id from brand table

Revision ID: e6b2f64cc8fe
Revises: 2cb720387109
Create Date: 2025-05-22 17:58:59.232536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b2f64cc8fe'
down_revision: Union[str, None] = '2cb720387109'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.drop_constraint('brands_sub_category_id_fkey', type_='foreignkey')
        batch_op.drop_column('sub_category_id')

    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sub_categories_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sub_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sub_categories_id'))

    with op.batch_alter_table('brands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('brands_sub_category_id_fkey', 'sub_categories', ['sub_category_id'], ['id'])

    # ### end Alembic commands ###
